transfer_functions: transfer_functions.ml
	ocamlopt -cc "g++" -I /usr/lib/ocaml/apron -o transfer_functions \
		/usr/lib/ocaml/bigarray.cmxa \
		/usr/lib/ocaml/apron/gmp.cmxa \
		/usr/lib/ocaml/apron/apron.cmxa \
		/usr/lib/ocaml/apron/ppl.cmxa \
		transfer_functions.ml
